AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an Amazon EFS file system and mount target and
  associates it with Amazon EC2 instances in an Auto Scaling group. **WARNING** This
  template creates Amazon EC2 instances and related resources. You will be billed
  for the AWS resources used if you create a stack from this template.
Parameters:
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: The SubnetId in your Virtual Private Cloud (VPC)
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  NfsBatch:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      BackupPolicy: 
        Status: DISABLED
      Encrypted: false
      FileSystemTags:
      - Key: Name
        Value: nfs_batch
      AvailabilityZoneName:
        Ref: AvailabilityZone
      ProvisionedThroughputInMibps: 100.0
      ThroughputMode: provisioned
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: NfsBatch
      SubnetId:
        Ref: Subnet
      SecurityGroups: 
        - Ref: SecurityGroup